### ISSUE TITLE
Sign Up | FE

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#8]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/2060c0a3-b1f1-41cf-88bd-0e99f63c5023)

![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/171e72be-dc42-4732-acf9-5b952b2742ae)

- [x] Form _sign-up form_
- [x] Action _sign-up action flow_
- [x] Validation _shared with BE_

**User story:**
As a writer, I want to sign up for the aspiring writer's platform, So that I can enjoy all features.

**Acceptance criteria:**

- [x] The Sign Up page should include mandatory fields for entering email, First name/Last name, password, and the Sign Up button placed below the fields.
- [x] All fields should be marked as mandatory.
- [x] When a user didn't fill in all the mandatory fields he should get an error message "The <field_name> is required" below the empty field.
- [x] When a user enters an invalid email address he should get an error message "Please, enter a correct email".
- [x] When a user enters an invalid password he should get an error message "Please, enter a correct password". 
- [x] The Password field should accept lowercase latin letters, uppercase latin letters, digits, special characters. Minimal length - 4, maximal length - 20. (https://github.com/BinaryStudioAcademy/bsa-2023-writorium/issues/93)
- [x] The Email field should consist of a local and a domain part separated by a symbol @ and accept lowercase latin letters, uppercase latin letters, digits, special characters, dot.
- [x] The First name/Last name field should accept lowercase latin letters, uppercase latin letters.
- [x] The Sign Up button should be active after all fields are filled in.
- [x] The Sign Up button must be inactive during validation.
- [ ] User shoud get error message "An account using this email already exists" if user enters email which is already registered. (https://github.com/BinaryStudioAcademy/bsa-2023-writorium/issues/140)
- [ ] User should be directed to the article page after successful registration. (https://github.com/BinaryStudioAcademy/bsa-2023-writorium/issues/114)

**Comment by lera777** [comment]
**Description**
Fields for entering Email, First name, Last name, password are not marked as mandatory.

**Steps to reproduce:**

1 Open website https://writorium-development-1c771c6e3c1a.herokuapp.com/sign-up.
2 Pay attention to the Email, First name, Last name, password fields are not marked as mandatory

**Actual result:** 
The Email, First name, Last name, password fields are not marked as mandatory.

**Expected result:** 
The Email, First name, Last name, password fields are marked as mandatory.

**Additional information:**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/3552309f-b572-4f17-acc4-4d1abdc29808)

**Environment:**
OS: macOS Catalina 10.15.7
Browser: Google Chrome 116.0.5845.110

**Severity:**
Low

**Priority:**
Low

**Comment by lera777** [comment]
**Description**
The following special characters are not accepted in the Password field:  ” / ' ` [ ] | \

**Steps to reproduce:**

1 Open website https://writorium-development-1c771c6e3c1a.herokuapp.com/sign-up.
2 Enter special characters ( ” / ' ` [ ] | \ ) in the Password field.
3 Pay attention to the "Please, enter a correct password" error message is displayed.

**Actual result:**
The following special characters are not accepted in the Password field:  ” / ' ` [ ] | \

**Expected result:**
The following special characters are accepted in the Password field:  ” / ' ` [ ] | \

**Additional information:**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/ca36486a-21ce-4858-8853-c2bcffa97051)

**Environment:**
OS: macOS Catalina 10.15.7
Browser: Google Chrome 116.0.5845.110

**Severity:**
Low

**Priority:**
Medium

**Comment by lera777** [comment]
**Description**
The background image on the registration page does not match the design.

**Steps to reproduce:**

1 Open website https://writorium-development-1c771c6e3c1a.herokuapp.com/sign-up.
2 Pay attention to the background image does not match the design.

**Actual result:**
The background image on the registration page does not match the design.

**Expected result:**
The background image on the registration page matches the design..

**Additional information:**



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/583029ad-f964-45d2-965f-d57486ae50c4)



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/cd623488-2641-4e15-be2e-d3b20beabba9)



**Environment:**
OS: macOS Catalina 10.15.7
Browser: Google Chrome 116.0.5845.110

**Severity:**
Low

**Priority:**
Medium

**Comment by andanf-e** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-writorium/issues/8#issuecomment-1698522735
Check existing issues
https://github.com/BinaryStudioAcademy/bsa-2023-writorium/issues/92

**Comment by lera777** [comment]
**Description**
App layout is displayed broken when screen size is reduced.

**Steps to reproduce:**

1 Open website https://writorium-development-1c771c6e3c1a.herokuapp.com/sign-up.
2 Reduce screen size to 1107 x 573 px.
3 Pay attention to the application layout is displayed broken.

**Actual result:** 
App layout is displayed broken when screen size is reduced to 1107 x 573 px.

**Expected result:** 
The application layout is displayed as in design when the screen size is reduced.

**Additional information:**


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/5102ff8e-bc43-47b0-9587-79701aed4e17)




**Environment:**
OS: macOS Catalina 10.15.7
Browser: Google Chrome 116.0.5845.110

**Severity:**
Low

**Priority:**
Medium

**Comment by lera777** [comment]
**Description**
The color of the entered text in the Email, First name, Last Name and Password fields does not match the design.

**Steps to reproduce:**

1 Open website https://writorium-development-1c771c6e3c1a.herokuapp.com/sign-up.
2 Fill in the Email, First name, Last Name, Password fields.
3 Pay attention to the color of the entered text (#9da4ae) does not match the design (#282828 50%).

**Actual result:** 
The color of the entered text (#9da4ae) in the Email, First name, Last Name and Password fields does not match the design (#282828 50%).

**Expected result:** 
The color of the entered text in the Email, First name, Last Name and Password fields matches the design.

**Additional information:**


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/e4aceec8-b6c2-4147-a3e6-577bd65ff9cd)



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/f8c613b9-cd6c-4eb8-804a-e0b6cafb82bd)






**Environment:**
OS: macOS Catalina 10.15.7
Browser: Google Chrome 116.0.5845.110

**Severity:**
Low

**Priority:**
Medium

**Comment by artemmatiushenko1** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-writorium/issues/8#issuecomment-1698502610
@lera777 I'm not sure how we should mark the mandatory fields, do we need to add an asterisk to the label? Something like on the image?
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/71723893/bc24eb3a-ecde-42be-9079-b39ea9161193)

**Comment by lera777** [comment]
**Description**
The color of placeholder in the Email, First name, Last Name and Password fields does not match the design.

**Steps to reproduce:**

1 Open website https://writorium-development-1c771c6e3c1a.herokuapp.com/sign-up.
2 Pay attention to the color of placeholder (#000000)  in the Email, First name, Last Name and Password fields does not match the design ( rgba(157, 164, 174, 1)).

**Actual result:** 
The color of placeholder (#000000) in the Email, First name, Last Name and Password fields does not match the design (rgba(157, 164, 174, 1).

**Expected result:** 
The color of placeholder in the Email, First name, Last Name and Password fields matches the design.

**Additional information:**


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/ca2f896e-ce97-40ad-979b-580d7b9e7479)



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/58594f19-f893-4ec1-b8e5-e90f807306aa)






**Environment:**
OS: macOS Catalina 10.15.7
Browser: Google Chrome 116.0.5845.110

**Severity:**
Low

**Priority:**
Medium
